// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-Byei-SNMD824dfR4kL7Jcw80Pq5zu0',
    appId: '1:645842511929:web:209a1f48b66e8ed2a045e8',
    messagingSenderId: '645842511929',
    projectId: 'attendease-cbc6f',
    authDomain: 'attendease-cbc6f.firebaseapp.com',
    storageBucket: 'attendease-cbc6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd7lkRSjGboHofb9foEh29cHwvz4ocYb8',
    appId: '1:645842511929:android:a79bc7d4c4db80afa045e8',
    messagingSenderId: '645842511929',
    projectId: 'attendease-cbc6f',
    storageBucket: 'attendease-cbc6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf1fXBPGyHV3FyYOvko3cPMZp_sZ0rrt0',
    appId: '1:645842511929:ios:60676ef619243669a045e8',
    messagingSenderId: '645842511929',
    projectId: 'attendease-cbc6f',
    storageBucket: 'attendease-cbc6f.firebasestorage.app',
    iosBundleId: 'com.example.attendEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf1fXBPGyHV3FyYOvko3cPMZp_sZ0rrt0',
    appId: '1:645842511929:ios:60676ef619243669a045e8',
    messagingSenderId: '645842511929',
    projectId: 'attendease-cbc6f',
    storageBucket: 'attendease-cbc6f.firebasestorage.app',
    iosBundleId: 'com.example.attendEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD-Byei-SNMD824dfR4kL7Jcw80Pq5zu0',
    appId: '1:645842511929:web:88efa48e8b400d60a045e8',
    messagingSenderId: '645842511929',
    projectId: 'attendease-cbc6f',
    authDomain: 'attendease-cbc6f.firebaseapp.com',
    storageBucket: 'attendease-cbc6f.firebasestorage.app',
  );
}
